### ISSUE TITLE
Is there a `Flask-Migrate`-like that works with this?

### ISSUE THREAD

**Issue by gnbezerra** [pallets-eco/flask-sqlalchemy-lite#16]
I finished the changes to go from Flask-SQLAlchemy to Flask-SQLAlchemy-Lite in my project, and I like how explicit you need to be when developing with it. However, the change broke my `Flask-Migrate` usage.

Whenever I try `flask db migrate -m "A revision message."`, I get the error:
```
AttributeError: 'SQLAlchemy' object has no attribute 'metadata'
```

Which, to be fair, is expected. I know I could go to plain Alembic as well, but it's so clunky that I wish there was a Flask-Migrate-Lite, or a fork of the original which works along with this.

I would even help in its development, given how overall frustrated I usually am when dealing with Alembic.

**Comment by pamelafox** [comment]
You can use Flask-Alembic, there’s a great page in the FSA-lite docs about
it:
https://flask-sqlalchemy-lite.readthedocs.io/en/latest/alembic/

**Comment by gnbezerra** [comment]
Flask-Alembic worked like a charm! Thank you so much.
