### ISSUE TITLE
Testing docs cuts off mid-sentence

### ISSUE THREAD

**Issue by pamelafox** [pallets-eco/flask-sqlalchemy-lite#6]
https://github.com/pallets-eco/flask-sqlalchemy-lite/blob/main/docs/testing.md#tests cuts off mid sentence.

I assume that's intended to have an example of tests you'd write with the suggested fixtures.

**Comment by thomthom** [comment]
I noticed the same thing. Curious if it would be much different than the flask-alchemy docs:
https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/contexts/#tests

**Comment by davidism** [comment]
Trying to remember if I had something else in mind, like "here's an example test that adds data then makes a request" or if this was just a leftover from brainstorming the sections that I did write. 🤔

**Comment by pamelafox** [comment]
I just went through the process of testing with FSA-Lite myself, and I do think it'd be helpful to show the app_context fixture, as I ended up using that whenever I needed to use db.session in a test.

Example tests could be good too. I can send a PR next week with some ideas.
